# Generated by Django 3.2.5 on 2021-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200, null=True)),
                ('adress', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('adress', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
