# Generated by Django 3.2.5 on 2021-08-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docteur',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
