# Generated by Django 3.2.5 on 2021-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0002_alter_patients_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], default='', max_length=200),
        ),
    ]
