# Generated by Django 3.2.5 on 2021-09-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0003_alter_utilisateur_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
