# Generated by Django 3.2.5 on 2021-09-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0006_auto_20210929_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_supservisor',
            field=models.BooleanField(default=False),
        ),
    ]
