# Generated by Django 3.2.5 on 2021-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0008_auto_20210921_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], default='', max_length=200),
        ),
    ]
