# Generated by Django 3.2.5 on 2021-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0008_auto_20210929_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_supservisor',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sex',
            field=models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], default='', max_length=200),
        ),
    ]
