# Generated by Django 3.2.5 on 2021-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0009_auto_20210929_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='sex',
            field=models.CharField(choices=[('FEMININ', 'feminin'), ('MASCULIN', 'masculin')], default='', max_length=200),
        ),
    ]
