# Generated by Django 3.2.5 on 2021-09-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0009_auto_20210921_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='latitude',
            field=models.DecimalField(decimal_places=19, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='longitude',
            field=models.DecimalField(decimal_places=19, max_digits=20),
        ),
    ]
