# Generated by Django 3.2.5 on 2021-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0010_auto_20210921_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(choices=[('FEMININ', 'feminin'), ('MASCULIN', 'masculin')], default='', max_length=200),
        ),
    ]
