# Generated by Django 3.2.5 on 2021-09-27 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientsApp', '0012_auto_20210923_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(default='', max_length=500)),
                ('sex', models.CharField(choices=[('FEMININ', 'feminin'), ('MASCULIN', 'masculin')], default='', max_length=200)),
                ('birth_date', models.DateField()),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patientsapp_utilisateur_patient_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
